In [1]:
#11). Repeat b), c), d), e) in Q2, by using Python on the HW1.csv data set.

#Import Python Libraries
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
from IPython.display import display, HTML

In [2]:
df=pd.read_csv('HW1.csv')

In [3]:
df.head()

   Cust ID Gender  Income  Age  Rentals  Avg Per Visit Incidentals   Genre
0        1      M   45000   25       27            2.5         Yes  Action
1        2      F   54000   33       12            3.4          No   Drama
2        3      F   32000   20       42            1.6          No  Comedy
3        4      F   59000   70       16            4.2         Yes   Drama
4        5      M   37000   35       25            3.2         Yes  Action

In [4]:
#b)Use min-max normalization to transform the values of the Income attribute onto the range [1-5].

# Normalization method  Min-max normalization [1,5]
df["Income_Min-max"]=((df["Income"]-df["Income"].min())/(df["Income"].max()-df["Income"].min()))*(4)+1
display(HTML(df.head(50).to_html()))

In [5]:
#c)Use z-score normalization to standardize the values of the age attribute.

from scipy.stats import zscore
df[['Age_z-score']] = zscore(df[['Age']])
display(HTML(df.head(50).to_html()))

In [6]:
# Define the bins and labels
bins = [1, 21, 41, float('inf')]
labels = ['Young', 'MidAge', 'Old']
# Creating a new column called 'Age_Category' for discretized values
df['Age_discretization'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)
display(HTML(df.head(50).to_html()))

In [11]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
df2=pd.read_csv('HW1.csv')
# Use LabelEncoder to convert the nominal variable 'Gender' to binary (0 for 'F', 1 for 'M')
le = LabelEncoder()
df2['Gender'] = le.fit_transform(df2['Gender'])
print(df2)
#We can also use if loop to get a similar output

    Cust ID  Gender  Income  Age  Rentals  Avg Per Visit Incidentals   Genre
0         1       1   45000   25       27            2.5         Yes  Action
1         2       0   54000   33       12            3.4          No   Drama
2         3       0   32000   20       42            1.6          No  Comedy
3         4       0   59000   70       16            4.2         Yes   Drama
4         5       1   37000   35       25            3.2         Yes  Action
5         6       1   18000   20       33            1.7          No  Action
6         7       0   29000   45       19            3.8          No   Drama
7         8       1   74000   25       31            2.4         Yes  Action
8         9       1   38000   21       18            2.1          No  Comedy
9        10       0   65000   40       21            3.3          No   Drama
10       11       0   41000   22       48            2.3         Yes   Drama
11       12       0   26000   22       29            2.9         Yes  Action
12       13       1   83000   46       14            3.6          No  Comedy
13       14       1   45000   36       24            2.7          No   Drama
14       15       1   68000   30       36            2.7         Yes  Comedy
15       16       1   17000   19       26            2.2         Yes  Action
16       17       1   36000   35       28            3.5         Yes   Drama
17       18       0    6000   16       39            1.8         Yes  Action
18       19       0   24000   25       41            3.1          No  Comedy
19       20       1   12000   16       23            2.2         Yes  Action
20       21       0   47000   52       11            3.1          No   Drama
21       22       1   25000   33       16            2.9         Yes   Drama
22       23       0    2000   15       30            2.5          No  Comedy
23       24       0   79000   35       22            3.8         Yes   Drama
24       25       1    1000   16       25            1.4         Yes  Comedy
25       26       0   56000   35       40            2.6         Yes  Action
26       27       0   62000   47       32            3.6          No   Drama
27       28       1   57000   52       22            4.1          No  Comedy
28       29       0   15000   18       37            2.1         Yes  Action
29       30       1   41000   25       17            1.4         Yes  Action
30       31       0   49000   56       15            3.2          No  Comedy
31       32       1   47000   30       21            3.1         Yes   Drama
32       33       1   23000   25       28            2.7          No  Action
33       34       0   29000   32       19            2.9         Yes  Action
34       35       1   74000   29       43            4.6         Yes  Action
35       36       0   29000   21       34            2.3          No  Comedy
36       37       1   89000   46       12            1.2          No  Comedy
37       38       1   41000   38       20            3.3         Yes   Drama
38       39       0   68000   35       19            3.9          No  Comedy
39       40       1   17000   19       32            1.8          No  Action
40       41       0   50000   33       17            1.4          No   Drama
41       42       1   32000   25       26            2.2         Yes  Action
42       43       0   49000   28       48            3.3         Yes   Drama
43       44       1   35000   24       24            1.7          No   Drama
44       45       1   56000   38       30            3.5         Yes   Drama
45       46       0   57000   43        9            1.1          No   Drama
46       47       0   69000   35       22            2.8         Yes   Drama
47       48       0   52000   47       14            1.6          No   Drama
48       49       1   31000   25       42            3.4         Yes  Action
49       50       1   24000   20       33            4.7          No  Action

In [13]:
le = LabelEncoder()
df2['Incidentals'] = le.fit_transform(df2['Incidentals'])
print(df2)

    Cust ID  Gender  Income  Age  Rentals  Avg Per Visit  Incidentals   Genre
0         1       1   45000   25       27            2.5            1  Action
1         2       0   54000   33       12            3.4            0   Drama
2         3       0   32000   20       42            1.6            0  Comedy
3         4       0   59000   70       16            4.2            1   Drama
4         5       1   37000   35       25            3.2            1  Action
5         6       1   18000   20       33            1.7            0  Action
6         7       0   29000   45       19            3.8            0   Drama
7         8       1   74000   25       31            2.4            1  Action
8         9       1   38000   21       18            2.1            0  Comedy
9        10       0   65000   40       21            3.3            0   Drama
10       11       0   41000   22       48            2.3            1   Drama
11       12       0   26000   22       29            2.9            1  Action
12       13       1   83000   46       14            3.6            0  Comedy
13       14       1   45000   36       24            2.7            0   Drama
14       15       1   68000   30       36            2.7            1  Comedy
15       16       1   17000   19       26            2.2            1  Action
16       17       1   36000   35       28            3.5            1   Drama
17       18       0    6000   16       39            1.8            1  Action
18       19       0   24000   25       41            3.1            0  Comedy
19       20       1   12000   16       23            2.2            1  Action
20       21       0   47000   52       11            3.1            0   Drama
21       22       1   25000   33       16            2.9            1   Drama
22       23       0    2000   15       30            2.5            0  Comedy
23       24       0   79000   35       22            3.8            1   Drama
24       25       1    1000   16       25            1.4            1  Comedy
25       26       0   56000   35       40            2.6            1  Action
26       27       0   62000   47       32            3.6            0   Drama
27       28       1   57000   52       22            4.1            0  Comedy
28       29       0   15000   18       37            2.1            1  Action
29       30       1   41000   25       17            1.4            1  Action
30       31       0   49000   56       15            3.2            0  Comedy
31       32       1   47000   30       21            3.1            1   Drama
32       33       1   23000   25       28            2.7            0  Action
33       34       0   29000   32       19            2.9            1  Action
34       35       1   74000   29       43            4.6            1  Action
35       36       0   29000   21       34            2.3            0  Comedy
36       37       1   89000   46       12            1.2            0  Comedy
37       38       1   41000   38       20            3.3            1   Drama
38       39       0   68000   35       19            3.9            0  Comedy
39       40       1   17000   19       32            1.8            0  Action
40       41       0   50000   33       17            1.4            0   Drama
41       42       1   32000   25       26            2.2            1  Action
42       43       0   49000   28       48            3.3            1   Drama
43       44       1   35000   24       24            1.7            0   Drama
44       45       1   56000   38       30            3.5            1   Drama
45       46       0   57000   43        9            1.1            0   Drama
46       47       0   69000   35       22            2.8            1   Drama
47       48       0   52000   47       14            1.6            0   Drama
48       49       1   31000   25       42            3.4            1  Action
49       50       1   24000   20       33            4.7            0  Action

In [17]:


df = pd.DataFrame(df2)

# Initialize new columns with 0
df['Genre_Action'] = 0
df['Genre_Comedy'] = 0


for index, row in df.iterrows():
    if row['Genre'] == 'Action':
        df.at[index, 'Genre_Action'] = 1
    elif row['Genre'] == 'Comedy':
        df.at[index, 'Genre_Comedy'] = 1


df = df.drop('Genre', axis=1)
print(df)

    Cust ID  Gender  Income  Age  Rentals  Avg Per Visit  Incidentals  \
0         1       1   45000   25       27            2.5            1
1         2       0   54000   33       12            3.4            0
2         3       0   32000   20       42            1.6            0
3         4       0   59000   70       16            4.2            1
4         5       1   37000   35       25            3.2            1
5         6       1   18000   20       33            1.7            0
6         7       0   29000   45       19            3.8            0
7         8       1   74000   25       31            2.4            1
8         9       1   38000   21       18            2.1            0
9        10       0   65000   40       21            3.3            0
10       11       0   41000   22       48            2.3            1
11       12       0   26000   22       29            2.9            1
12       13       1   83000   46       14            3.6            0
13       14       1   45000   36       24            2.7            0
14       15       1   68000   30       36            2.7            1
15       16       1   17000   19       26            2.2            1
16       17       1   36000   35       28            3.5            1
17       18       0    6000   16       39            1.8            1
18       19       0   24000   25       41            3.1            0
19       20       1   12000   16       23            2.2            1
20       21       0   47000   52       11            3.1            0
21       22       1   25000   33       16            2.9            1
22       23       0    2000   15       30            2.5            0
23       24       0   79000   35       22            3.8            1
24       25       1    1000   16       25            1.4            1
25       26       0   56000   35       40            2.6            1
26       27       0   62000   47       32            3.6            0
27       28       1   57000   52       22            4.1            0
28       29       0   15000   18       37            2.1            1
29       30       1   41000   25       17            1.4            1
30       31       0   49000   56       15            3.2            0
31       32       1   47000   30       21            3.1            1
32       33       1   23000   25       28            2.7            0
33       34       0   29000   32       19            2.9            1
34       35       1   74000   29       43            4.6            1
35       36       0   29000   21       34            2.3            0
36       37       1   89000   46       12            1.2            0
37       38       1   41000   38       20            3.3            1
38       39       0   68000   35       19            3.9            0
39       40       1   17000   19       32            1.8            0
40       41       0   50000   33       17            1.4            0
41       42       1   32000   25       26            2.2            1
42       43       0   49000   28       48            3.3            1
43       44       1   35000   24       24            1.7            0
44       45       1   56000   38       30            3.5            1
45       46       0   57000   43        9            1.1            0
46       47       0   69000   35       22            2.8            1
47       48       0   52000   47       14            1.6            0
48       49       1   31000   25       42            3.4            1
49       50       1   24000   20       33            4.7            0

    Genre_Action  Genre_Comedy
0              1             0
1              0             0
2              0             1
3              0             0
4              1             0
5              1             0
6              0             0
7              1             0
8              0             1
9              0             0
10             0             0
11             1             0
12             0             1
13             0             0
14             0             1
15             1             0
16             0             0
17             1             0
18             0             1
19             1             0
20             0             0
21             0             0
22             0             1
23             0             0
24             0             1
25             1             0
26             0             0
27             0             1
28             1             0
29             1             0
30             0             1
31             0             0
32             1             0
33             1             0
34             1             0
35             0             1
36             0             1
37             0             0
38             0             1
39             1             0
40             0             0
41             1             0
42             0             0
43             0             0
44             0             0
45             0             0
46             0             0
47             0             0
48             1             0
49             1             0

In [20]:
2)numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64'] 
# get column names 
cols_numeric = df.select_dtypes(include=numerics).columns.tolist() 
df_numeric = df[cols_numeric] 
display(HTML(df.head(5).to_html())) 
corr=df_numeric.corr(method='pearson') 
display(HTML(corr.to_html()))

In [21]:
#Rentals are comparitively highly correlated with Age(negative correaltion) and Genre Action

In [25]:
df=pd.read_csv('HW1.csv')
from scipy.stats import f_oneway  

genre_action = df[df['Genre']=='Action']['Age']
genre_drama = df[df['Genre']=='Drama']['Age']
genre_comedy = df[df['Genre']=='Comedy']['Age']  
print(f_oneway(genre_action, genre_drama,genre_comedy))

F_onewayResult(statistic=8.830189952460437, pvalue=0.0005550099142521056)

In [26]:
from scipy.stats import f_oneway  

genre_action = df[df['Genre']=='Action']['Rentals']
genre_drama = df[df['Genre']=='Drama']['Rentals']
genre_comedy = df[df['Genre']=='Comedy']['Rentals']  
print(f_oneway(genre_action, genre_drama,genre_comedy))

F_onewayResult(statistic=3.1956455356365185, pvalue=0.049974070580121745)

In [31]:
from scipy.stats import f_oneway  

genre_action = df[df['Genre']=='Action']['Income']
genre_drama = df[df['Genre']=='Drama']['Income']
genre_comedy = df[df['Genre']=='Comedy']['Income']  
print(f_oneway(genre_action, genre_drama,genre_comedy))

F_onewayResult(statistic=3.8076066330686538, pvalue=0.029337916333349683)

In [33]:
# The F_onewayResult(statistic how much the variable is dependent on Genre.Higher the value of it more it is dependable.
#It has significant dependence but not strong. Age has highest dependency comparitively